-- Databricks notebook source
-- MAGIC %python
-- MAGIC dbutils.widgets.text("stg_schema", "")
-- MAGIC dbutils.widgets.text("stg_container", "")
-- MAGIC dbutils.widgets.text("rej_schema", "")
-- MAGIC dbutils.widgets.text("rej_container", "")
-- MAGIC dbutils.widgets.text("landing_storage", "")
-- MAGIC dbutils.widgets.text("staging_storage", "")

-- COMMAND ----------

USE CATALOG CI_ID;
CREATE DATABASE IF NOT EXISTS stg_crm-mcm;
CREATE DATABASE IF NOT EXISTS rej_crm-mcm;

-- COMMAND ----------

CREATE OR REPLACE TABLE CI_ID.stg_crm-mcm.MEM_COUPON
(
    ISPHYSICALCOUPON BOOLEAN NOT NULL,
    ISECOUPON BOOLEAN NOT NULL,
    COUPONTYPECODE STRING NOT NULL,
    FACEVALUE DECIMAL,
    DISCOUNTPERCENTAGE INT,
    MULTIPLESCANINDICATOR BOOLEAN,
    MAXSCANPERCOUPON INT,
    MOBILEAPPINDICATOR BOOLEAN,
    FAMILYCOUPONINDICATOR BOOLEAN,
    ISADMISSIONCOUPON BOOLEAN,
    COUPONVALUE INT,
    COUPONSTARTDATE DATE,
    COUPONENDDATE DATE,
    OFFERCODE STRING NOT NULL,
    COUPONPROGRAMCODE STRING NOT NULL,
    CAMPAIGNCODE STRING,
    CAMPAIGNNAME STRING,
    CAMPAIGNSTARTDATE TIMESTAMP,
    CAMPAIGNENDDATE TIMESTAMP,
    COMMUNICATIONCODE STRING,
    CAMPAIGNCHANNEL STRING,
    QUANTITYISSUED INT,
    LONGCODE STRING NOT NULL,
    BURNQUANTITY INT,
    MEMBERSHIPACCOUNTNUMBER STRING,
    FAMILYMEMBERNUMBER STRING,
    COUPONSTATUS INT NOT NULL,
    COUPONUPDATEDBY STRING,
    COUPONUPDATEDON TIMESTAMP NOT NULL,
    COUPONCREATEDON TIMESTAMP NOT NULL,
    ISSTAMP BOOLEAN,
    ETL_LAST_UPDATE_DATETIME TIMESTAMP,
    ETL_LAST_UPDATED_BY STRING,
    ETL_CREATED_DATETIME TIMESTAMP,
    ETL_CREATED_BY STRING,
    ETL_PROCESS_DATETIME TIMESTAMP,
    CONSTRAINT PK_MEM_COUPON PRIMARY KEY (OFFERCODE)
    -- FK MembershipAccountNumber and FamilyMemberNumber with CRM-MB
)
USING DELTA LOCATION 'abfss://crm-mcm@adlsedapstgsatea002.dfs.core.windows.net/MEM_COUPON'

-- COMMAND ----------

CREATE OR REPLACE TABLE CI_ID.rej_crm-mcm.MEM_COUPON
(
    ISPHYSICALCOUPON BOOLEAN,
    ISECOUPON BOOLEAN,
    COUPONTYPECODE STRING,
    FACEVALUE DECIMAL,
    DISCOUNTPERCENTAGE INT,
    MULTIPLESCANINDICATOR BOOLEAN,
    MAXSCANPERCOUPON INT,
    MOBILEAPPINDICATOR BOOLEAN,
    FAMILYCOUPONINDICATOR BOOLEAN,
    ISADMISSIONCOUPON BOOLEAN,
    COUPONVALUE INT,
    COUPONSTARTDATE DATE,
    COUPONENDDATE DATE,
    OFFERCODE STRING,
    COUPONPROGRAMCODE STRING,
    CAMPAIGNCODE STRING,
    CAMPAIGNNAME STRING,
    CAMPAIGNSTARTDATE TIMESTAMP,
    CAMPAIGNENDDATE TIMESTAMP,
    COMMUNICATIONCODE STRING,
    CAMPAIGNCHANNEL STRING,
    QUANTITYISSUED INT,
    LONGCODE STRING,
    BURNQUANTITY INT,
    MEMBERSHIPACCOUNTNUMBER STRING,
    FAMILYMEMBERNUMBER STRING,
    COUPONSTATUS INT,
    COUPONUPDATEDBY STRING,
    COUPONUPDATEDON TIMESTAMP,
    COUPONCREATEDON TIMESTAMP,
    ISSTAMP BOOLEAN,
    REJECT_MESSAGE STRING,
    RUN_ID STRING
)
USING DELTA LOCATION 'abfss://rej_crm-mcm@adlsedaplndsatea001.dfs.core.windows.net/MQTT/mem_coupon/rejected'

-- COMMAND ----------

CREATE OR REPLACE TABLE CI_ID.stg_crm-mcm.SCANNING_HISTORY
(
    VENUE STRING,
    TIME TIMESTAMP,
    OFFERCODE STRING NOT NULL,
    LONGCODE STRING NOT NULL,
    TRANSACTIONSTATUS STRING NOT NULL,
    USEDAMOUNT INT NOT NULL,
    TRANSACTIONTYPE STRING NOT NULL,
    ETL_LAST_UPDATE_DATETIME TIMESTAMP,
    ETL_LAST_UPDATED_BY STRING,
    ETL_CREATED_DATETIME TIMESTAMP,
    ETL_CREATED_BY STRING,
    ETL_PROCESS_DATETIME TIMESTAMP
)
USING DELTA LOCATION 'abfss://crm-mcm@adlsedapstgsatea002.dfs.core.windows.net/SCANNING_HISTORY'

-- COMMAND ----------

CREATE OR REPLACE TABLE CI_ID.rej_crm-mcm.SCANNING_HISTORY
(
    VENUE STRING,
    TIME TIMESTAMP,
    OFFERCODE STRING,
    LONGCODE STRING,
    TRANSACTIONSTATUS STRING,
    USEDAMOUNT INT,
    TRANSACTIONTYPE STRING,
    REJECT_MESSAGE STRING,
    RUN_ID STRING
)
USING DELTA LOCATION 'abfss://rej_crm-mcm@adlsedaplndsatea001.dfs.core.windows.net/MQTT/scanning_history/rejected'

-- COMMAND ----------


